### PR TITLE
exchange: fix The specified counter could not be found

### LINKED ISSUE #1904: Coud not get MS Exchange Transport Queues in metrics
### Problem Statement

I am trying to get MS Exchange Server 2016 Queues monitoring, i have installed windows_exporter on my exchange server using config.yaml. Using OS Windows Server 2019 and Exchange Server 2016.

# example configuration file for windows_exporter
collectors:
  enabled: cpu,cpu_info,exchange,iis,logical_disk,logon,memory,net,os,performancecounter,process,remote_fx,service,system,tcp,time,terminal_services,textfile
collector:
  service:
    include: "windows_exporter"
log:
  level: warn

but i am unable to get TransportQueues metrics at “localhost:9182/metrics”.
I am getting following metrics here
windows_exchange_http_proxy
windows_exchange_ldap
windows_exchange_workload
and some windows_iis_current_application_pool_state{app="MSExchangeAutodiscoverAppPool",state="Delete Pending"} 0
i have added MSExchangeTransport Queues in Windows Performance Monitor Counter.

I have followed a blog post [https://bidhankhatri.com.np/monitoring/windows-machine-monitoring/] but to no avail.

Thanks in advance.

### Environment

- windows_exporter Version: v0.30.4
- Windows Server Version: Windows Server 2019

### LINKED ISSUE #1991: Issue with Exchange collector and specific Exchange metrics
### Current Behavior

Transport queues, AvailabilityService and Autodiscover failed to create collector in the exchange collector. 

### Expected Behavior

All collectors in the exchange collector works with previous versions. 
Im expecting it to work in this version. 

### Steps To Reproduce

```Markdown
Install windows_exporter 0.30.2 on Exchange 2019 server. 

Path to executable on windows_exporter: "C:\Program Files\windows_exporter\windows_exporter.exe" --config.file="C:\Program Files\windows_exporter\config.yaml" --web.config.file="C:\Program Files\windows_exporter\web-config.yml"

config.yaml has exchange collector enabled like this:
collectors:
  enabled: cpu,logical_disk,net,memory,system,pagefile,textfile,service,scheduled_task,iis,exchange
```

### Environment

- windows_exporter Version: 0.30.2  (It works fine in 0.29.2)
- Windows Server Version: windows server 2022, exchange server 2019 CU15

### windows_exporter logs

```shell
time=2025-04-11T07:10:02.244Z level=WARN source=collection.go:239 msg="couldn't initialize collector" err="error build collector exchange: failed to build TransportQueues collector: failed to create MSExchangeTransport Queues collector: failed to initialize collector: failed to add counter \\MSExchangeTransport Queues(*)\\Shadow Queue Length: The specified counter could not be found.\r\n\nfailed to build AvailabilityService collector: failed to create MSExchange Availability Service collector: failed to initialize collector: failed to add counter \\MSExchange Availability Service(*)\\Requests/sec: The specified counter could not be found.\r\n\nfailed to build Autodiscover collector: failed to create MSExchange Autodiscover collector: failed to initialize collector: failed to add counter \\MSExchange Autodiscover(*)\\Requests/sec: The specified object was not found on the computer.\r\n"
```

### Anything else?

We have tried to rebuild counters, issue persists. 
When running "typeperf -qx > counters.txt" I can see that the counters are available.

[counters.txt](https://github.com/user-attachments/files/19700709/counters.txt)

### PR DESCRIPTION
**Pull request by jkroepke**
#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

- fixes #1991 
- fixes #1904

#### Checklist

Complete these before marking the PR as `ready to review`:

- [x] [DCO](https://github.com/prometheus-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] The PR title has a summary of the changes and the area they affect
- [ ] The PR body has a summary to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

File: internal/collector/exchange/exchange_availability_service.go [hunk 1]
```diff
@@ -33,7 +33,7 @@ type collectorAvailabilityService struct {
 }
 
 type perfDataCounterValuesAvailabilityService struct {
-	RequestsPerSec float64 `perfdata:"Requests/sec"`
+	availabilityRequestsPerSec float64 `perfdata:"Availability Requests (sec)"`
```
Comment (jkroepke) [inline internal/collector/exchange/exchange_availability_service.go:36]:
```suggestion
	AvailabilityRequestsPerSec float64 `perfdata:"Availability Requests (sec)"`
```

File: internal/collector/exchange/exchange_availability_service.go [hunk 2]
```diff
@@ -64,7 +64,7 @@ func (c *Collector) collectAvailabilityService(ch chan<- prometheus.Metric) erro
 		ch <- prometheus.MustNewConstMetric(
 			c.availabilityRequestsSec,
 			prometheus.CounterValue,
-			data.RequestsPerSec,
+			data.availabilityRequestsPerSec,
```
Comment (jkroepke) [inline internal/collector/exchange/exchange_availability_service.go:67]:
```suggestion
			data.AvailabilityRequestsPerSec,
```
