### PR TITLE
Continue OS collector on absent paging file

### LINKED ISSUE #939: os collector fails when paging file is disabled (>= v0.17.0)
Having the Windows paging file disabled on all volumes results in the "os" collector failing on v0.17.0 or newer with below error.
Either running an older version (i.e. v0.16.0) or setting a paging file again (w/ system reboot for some reason) mitigates this, but would be great if this could be fixed in the exporter/collector again in an upcoming version.
Tested on both Windows 10 LTSC 2021 and Windows Server 2022.
```
failed collecting os metrics:<nil> The system cannot find the file specified.
collector os failed after 0.003015s: The system cannot find the file specified.
```

### PR DESCRIPTION
**Pull request by breed808**
Inactive or missing paging file should not be cause for OS collector to
fail.
Instead, log the error and continue with OS collection.

Resolves #939

### CODE REVIEW

**Comment by breed808** [comment]
Omitting the metric may reduce confusion as to why a paging file is 0 bytes in size. I'll amend the PR :+1:

File: collector/os.go [hunk 1]
```diff
@@ -261,12 +257,21 @@ func (c *OSCollector) collect(ctx *ScrapeContext, ch chan<- prometheus.Metric) (
 		timezoneName,
 	)
 
-	ch <- prometheus.MustNewConstMetric(
-		c.PagingFreeBytes,
-		prometheus.GaugeValue,
-		pfb,
-	)
-
+	if pagingErr == nil {
```
Comment (petemounce) [inline collector/os.go:260]: Could this be handled closer to the error return possibility 80 lines higher? There's been another, different registry access since; I would find it easier to follow the flow with less to read.

(Obviously, I'm also random person on the internet; I hope review comments are welcome. I'm coming from #923 where I tried to understand an error from near here and haven't yet)

File: collector/os.go [hunk 2]
```diff
@@ -261,12 +257,21 @@ func (c *OSCollector) collect(ctx *ScrapeContext, ch chan<- prometheus.Metric) (
...
+			pfb,
+		)
+
+		ch <- prometheus.MustNewConstMetric(
+			c.PagingLimitBytes,
+			prometheus.GaugeValue,
+			fsipf,
+		)
+	} else {
+		log.Debugln("Could not find SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management key. windows_os_paging_free_bytes and windows_os_paging_limit_bytes will be omitted.")
```
Comment (petemounce) [inline collector/os.go:273]: Could the fact that this is in the hklm hive please be reflected into the log message? There are several to choose from when verifying the system state vs code behaviour.

```suggestion
		log.Debugln("Could not find HKLM:\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management key. windows_os_paging_free_bytes and windows_os_paging_limit_bytes will be omitted.")
```

Or extract a variable for the paths as well?

**Review by petemounce — COMMENTED** [review]
Thanks for your efforts to fix, I really appreciate it! I hope my comments are welcome; I'm not a maintainer or anything.

File: collector/os.go (hunk 1 above)
Comment (breed808) [reply collector/os.go:260]: I agree that the flow of the collector is made more difficult by the change, but the `pagingFiles` variable is required shortly afterwards to populate the `fsipf` and `pfb` variables, while the metric exports to the channel all occur at the same time to improve readability.

So I don't think it's worth trying to rearrange the `collect` function to group `pagingErr` with the paging metrics.

File: collector/os.go (hunk 2 above)
Comment (breed808) [reply collector/os.go:273]: That's a good idea, I'll add `HKLM` to the log message.
